version: "3.8"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/   

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootsecretpassword
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=db-username
      - MYSQL_PASSWORD=db-password
    volumes:
      - ./src/db/sql/:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db

  attacker-app:
    build:
      context: ./attacker
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./attacker/:/flask-app/